version: "3"

services:
  next:
    build: ./app/
    container_name: next
    restart: always
    ports:
      - "3001:3001"
    command:
      "npm run build"

  nginx:
    image: nginx:1.17
    container_name: ngxe
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - next
